version: "2"
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=usersql
      - MYSQL_PASSWORD=123456
    #ports: 3306:3306
  app:
    depends_on:
      - db
    image: zevgenz/task3_docker
    container_name: app
    environment:
      - DB_USER=usersql
      - DB_PASS=123456
      - DB_NAME=petclinic
      - DB_HOST=db:3306
   # command: ping db
    ports:
      - "8080:8080"
    #volumes:
    #  - .:/code