---
- hosts: DB_VM
  #connection: local
  #remote_user: ec2-user #root #zevgenz #vagrant
  become: yes
  #become_method: sudo
  vars:
    db_user: '{{ DB_USER }}'
    db_pass: '{{ DB_PASS }}'
    db_host: '{{ DB_HOST }}'
    db_port: '{{ DB_PORT }}'
    db_name: '{{ DB_NAME }}'   

  tasks:
    - name: Update yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
        #become: yes

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - MySQL-python
        - mariadb-server
        
    - name: Start the MySQL service
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Removes test database
      mysql_db:
        name: test
        state: absent

    - name: Create new database
      mysql_db:
        name: '{{ db_name }}'
        state: present
        

    - name: Create new database user
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_pass }}'
        priv: '{{ db_name }}.*:ALL,GRANT'
        host: '{{ db_host }}'
        state: present
       
    - name: Copy cnf file
      template:
        src: ./my.cnf
        dest: /etc/my.cnf
        owner: root
        mode: 0600

    - name: Restart MySQL
      service:
        name: mariadb
        state: restarted

  handlers:
    - name: Restart MySQL
      service:
        name: mariadb
        state: restarted
