---
- hosts: DB_VM
  connection: local
  #remote_user: root #zevgenz #vagrant
  become: yes
  #become_method: sudo
  vars:
    db_name: '{{ DB_NAME }}'       
        #    src_dir: /home/vagrant/src
        #hackt_dir: "{{ src_dir }}/hackt"

  tasks:
    - name: Update yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
        #become: yes

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - MySQL-python
        - mariadb-server
                #- "@Development tools"
                #- guile
                #- libtool-ltdl-devel
                #- wget
              #- texinfo
      #become: yes
      
    - name: Start the MySQL service
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Removes test database
      mysql_db:
        name: test
        state: absent


    - name: Create new database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        #login_host: 10.0.10.11
        #login_password: demka
        #login_port: 3306
        #login_user: petclinic
        #notify:
        #- Restart MySQL

    - name: Create new database user
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_pass }}'
        priv: 'db_name.*:ALL,GRANT'
        state: present

    

  handlers:
    - name: Restart MySQL
      service:
        name: mariadb
        state: restarted
